description: >
  Mircea Baja's Posts
exclude: ['.ruby-version', 'Gemfile', 'Gemfile.lock']
github_username:  bajamircea
paginate: 100
title: bajamircea.github.io
url: 'http://bajamircea.github.io'
plugins: [jekyll-paginate, jekyll-feed]
