description: >
  Mircea Baja's Posts
exclude: ['.ruby-version', 'Gemfile', 'Gemfile.lock', 'code']
github_username:  bajamircea
paginate: 1000
title: bajamircea.github.io
url: 'http://bajamircea.github.io'
plugins: [jekyll-paginate, jekyll-feed]
future: true
